package app.termosh.core.ssh.exports

import app.termosh.domain.model.Server
import app.termosh.domain.model.ServerAuth
import app.termosh.domain.model.SshKey

/**
 * Генератор ~/.ssh/config из списка Server.
 *
 * Пароли и приватные ключи не выгружаются.
 * IdentityFile указывается как ~/.ssh/<fingerprint>.pub — путь условный,
 * пользователь сам решит, как назвать файлы ключей.
 */
object OpenSshConfigExporter {

    fun export(
        servers: List<Server>,
        keysById: Map<String, SshKey>,
        serversById: Map<String, Server>,
    ): String {
        if (servers.isEmpty()) return "# Termosh: нет серверов для экспорта\n"

        val sb = StringBuilder()
        sb.append("# Generated by Termosh\n")
        sb.append("# Date: ").append(java.util.Date()).append('\n')
        sb.append('\n')

        servers.forEach { s ->
            sb.append("Host ").append(sanitizeName(s.name)).append('\n')
            sb.append("    HostName ").append(s.host).append('\n')
            if (s.port != 22) sb.append("    Port ").append(s.port).append('\n')
            sb.append("    User ").append(s.username).append('\n')

            // ProxyJump
            s.proxyJumpId?.let { jid ->
                serversById[jid]?.let { j ->
                    sb.append("    ProxyJump ").append(sanitizeName(j.name)).append('\n')
                }
            }

            // IdentityFile
            if (s.auth is ServerAuth.Keys) {
                (s.auth as ServerAuth.Keys).keyIds.forEach { kid ->
                    keysById[kid]?.let { k ->
                        sb.append("    IdentityFile ~/.ssh/termosh_")
                            .append(k.fingerprintSha256.removePrefix("SHA256:").take(16))
                            .append(".pub\n")
                    }
                }
                sb.append("    IdentitiesOnly yes\n")
            }

            // Комментарии с доп. инфо
            if (s.tags.isNotEmpty()) {
                sb.append("    # Tags: ").append(s.tags.joinToString(", ")).append('\n')
            }
            if (s.useMosh) {
                sb.append("    # Termosh: mosh enabled\n")
            }

            sb.append('\n')
        }

        return sb.toString()
    }

    private fun sanitizeName(name: String): String {
        // OpenSSH: имя хоста без пробелов, табов и решётки
        val cleaned = name.trim().replace(Regex("[\\s#]+"), "-")
        return cleaned.ifEmpty { "host" }
    }
}
