package app.termosh.core.ssh.imports

import app.termosh.domain.model.Server
import app.termosh.domain.model.ServerAuth
import app.termosh.domain.model.SshKey

/**
 * Экспорт серверов в формат ~/.ssh/config.
 *
 * Пароли, приватные ключи и TOTP-секреты НЕ выгружаются — только метаданные.
 * Нестандартные для OpenSSH поля пишутся комментариями `# termosh:...`,
 * чтобы обратный импорт мог их восстановить.
 */
object OpenSshConfigWriter {

    fun write(
        servers: List<Server>,
        keys: Map<String, SshKey>,
        serverNames: Map<String, String>,
    ): String {
        val sb = StringBuilder()
        sb.append("# Generated by Termosh on ").append(System.currentTimeMillis()).append('\n')
        sb.append("# Secrets (пароли, приватные ключи) не экспортируются.\n\n")

        val seen = mutableMapOf<String, Int>()
        servers.forEach { s ->
            val base = alias(s)
            val n = (seen[base] ?: 0) + 1
            seen[base] = n
            val hostAlias = if (n == 1) base else "${base}_$n"

            sb.append("Host ").append(hostAlias).append('\n')
            sb.append("    HostName ").append(s.host).append('\n')
            sb.append("    User ").append(s.username).append('\n')
            if (s.port != 22) {
                sb.append("    Port ").append(s.port).append('\n')
            }

            s.proxyJumpId?.let { jid ->
                serverNames[jid]?.let { jn ->
                    sb.append("    ProxyJump ").append(jn.replace(Regex("\\s+"), "_")).append('\n')
                }
            }

            (s.auth as? ServerAuth.Keys)?.keyIds?.forEach { kid ->
                keys[kid]?.let { k ->
                    val fname = identityFileName(k)
                    sb.append("    # Termosh: ключ \"").append(k.comment ?: kid)
                        .append("\" — положить приватный ключ в ~/.ssh/").append(fname).append('\n')
                    sb.append("    IdentityFile ~/.ssh/").append(fname).append('\n')
                }
            }

            if (s.useMosh) sb.append("    # termosh:useMosh=true\n")
            if (s.tags.isNotEmpty()) {
                sb.append("    # termosh:tags=").append(s.tags.joinToString(",")).append('\n')
            }
            s.totpSecretId?.let {
                sb.append("    # termosh:totpSecretId=").append(it).append('\n')
            }
            if (s.startupCommands.isNotEmpty()) {
                sb.append("    # termosh:startup=")
                    .append(s.startupCommands.joinToString(";"))
                    .append('\n')
            }
            if (s.envVars.isNotEmpty()) {
                val ev = s.envVars.entries.joinToString(",") { "${it.key}=${it.value}" }
                sb.append("    # termosh:env=").append(ev).append('\n')
            }

            sb.append('\n')
        }
        return sb.toString()
    }

    private fun alias(s: Server): String {
        val base = s.name.ifBlank { "${s.username}@${s.host}" }
        return base.replace(Regex("\\s+"), "_")
    }

    private fun identityFileName(k: SshKey): String {
        val base = k.comment?.takeIf { it.isNotBlank() }
            ?: k.fingerprintSha256.removePrefix("SHA256:").take(12)
        return base.replace(Regex("[^A-Za-z0-9._-]"), "_") + ".key"
    }
}
